services:
  # java_app:
  #   container_name: java_app
  #   image: my-image/java_app:latest
  #   build: .
  #   ports:
  #     - ${SPRING_APPLICATION_PORT}:${SPRING_APPLICATION_PORT}
  #   environment:
  #     - DATABASE_URL=SPRING_DATASOURCE_URL
  #     - DATABASE_USERNAME=SPRING_DATASOURCE_USERNAME
  #     - DATABASE_PASSWORD=SPRING_DATASOURCE_PASSWORD
  #   depends_on:
  #     - db

  db:
    container_name: ${DB_HOST}
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pg_Data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080