services:
  java_app:
    container_name: java_app
    image: my-image/java_app:latest
    build: .
    ports:
      - ${JAVA_APP_PORT}:${JAVA_APP_PORT}
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:${DB_PORT}/${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - ${DB_HOST}

  java_db:
    container_name: ${DB_HOST}
    image: postgres:12
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_EmpData:/var/lib/postgresql/data

volumes:
  pg_EmpData: {}